---
title: "第13章 マーケットバスケットとクロスセリング"
output:
  html_document: 
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
    md_extensions: -ascii_identifiers
    df_print: "paged"
    highlight: "pygments"
    css: "template/style_ch.css"
    includes:
      in_header: "template/head.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# packages
library(plotly)
library(broom)
# library(pander)
library(knitr)

# data
apriori <- read.table("data/apriori.txt", header = T, sep = ",")
```

<div style="text-align: right;">
更新日：`r Sys.time()`
</div>

## データ
#### apriori.txt
```{r, echo=FALSE}
head(apriori)
```


## 3 マーケットバスケット分析
```{r, message=FALSE}
library(arules)

# transactions 形式へデータを変換
y.tran <- as.matrix(apriori, "transactions")

# アソシエーション分析の実行
rules <- apriori(y.tran, parameter = list(supp = 0.4, conf = 0.5))
```

```{r, message=FALSE}
# ルール数
print(rules)
```

**「set of 0 rules」**（ルール数がゼロ）と出力される場合は，`apriori` 関数の引数 `parameter = list(supp = 0.4, conf = 0.5)` の数値を小さくすればルールが抽出できる。ただし，小さくした分，分析結果の支持度や信頼度の水準は低くなる。


```{r, message=FALSE}
# リフト上位20ルール
inspect(head(sort(rules, by = "lift"), n = 20))
```
