---
title: ""
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    df_print: "paged"
    highlight: pygments
    # theme: lumen
    md_extensions: -ascii_identifiers
    css: "template/style_ch.css"
    includes:
      in_header: "template/head.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# packages
library(plotly)
library(broom)
# library(pander)
library(knitr)

# data
```

</br>

- データ出典：[Open psychology data: Raw data from online personality tests](https://openpsychometrics.org/_rawdata/)
- 質問文（日本語）は [Wikipedia のビッグファイブ（心理学）](https://ja.wikipedia.org/wiki/%E3%83%93%E3%83%83%E3%82%B0%E3%83%95%E3%82%A1%E3%82%A4%E3%83%96_(%E5%BF%83%E7%90%86%E5%AD%A6))を参考とした。

## 外向性（Extraversion）
| 変数 | 質問文（英語）                                  | 質問文（日本語）                                         |
| ---- | ----------------------------------------------- | -------------------------------------------------------- |
| E1   | I am the life of the party.                     | 私は盛り上げ役だ。                                       |
| E2   | I don't talk a lot.                             | 私はあまり喋らない。（逆転）                             |
| E3   | I feel comfortable around people.               | 私は多くの人といるとくつろぐ。                           |
| E4   | I keep in the background.                       | 私は大勢の人がいる中で話すつもりはない。（逆転）         |
| E5   | I start conversations.                          | 私からよく会話を始める。                                 |
| E6   | I have little to say.                           | 私は多くを語らない。（逆転）                             |
| E7   | I talk to a lot of different people at parties. | 私はパーティーではたくさんの色々な人たちと話す。         |
| E8   | I don't like to draw attention to myself.       | 私は周りのみんなから注目されるのが好きではない。（逆転） |
| E9   | I don't mind being the center of attention.     | 私はみんなからの注目の的であることを気にしない。         |
| E10  | I am quiet around strangers.                    | 私は見知らぬ人が周りにいる時は静かにしている。（逆転）   |


## 神経症的傾向（Neuroticism）
| 変数 | 質問文（英語）                 | 質問文（日本語）                                 |
| ---- | ------------------------------ | ------------------------------------------------ |
| N1   | I get stressed out easily.     | 私はストレスが溜まりやすい。                     |
| N2   | I am relaxed most of the time. | 私はほとんどの時間でリラックスしている。（逆転） |
| N3   | I worry about things.          | 私は物事を心配しがちだ。                         |
| N4   | I seldom feel blue.            | 私はブルーな気分になることは滅多にない。（逆転） |
| N5   | I am easily disturbed.         | 私は簡単に動揺する。                             |
| N6   | I get upset easily.            | 私はすぐにイライラする。                         |
| N7   | I change my mood a lot.        | 私は頻繁に気分が変わる。                         |
| N8   | I have frequent mood swings.   | 私は気分にムラがあることが多い。                 |
| N9   | I get irritated easily.        | 私は簡単にイライラする。                         |
| N10  | I often feel blue.             | 私はよくブルーな気分になる。                     |


## 協調性（Agreeableness）
| 変数 | 質問文（英語）                                  | 質問文（日本語）                                   |
| ---- | ----------------------------------------------- | -------------------------------------------------- |
| A1   | I feel little concern for others.               | 私は他の人のことをほとんど心配しません。（逆転）   |
| A2   | I am interested in people.                      | 私は人に興味がある。                               |
| A3   | I insult people.                                | 私は人を侮辱する。（逆転）                         |
| A4   | I sympathize with others' feelings.             | 私は他人の気持ちに共感する。                       |
| A5   | I am not interested in other people's problems. | 私は他の人が抱えている問題には興味がない。（逆転） |
| A6   | I have a soft heart.                            | 私には優しい心がある。                             |
| A7   | I am not really interested in others.           | 私は他人にはあまり興味がない。（逆転）             |
| A8   | I take time out for others.                     | 私は他の人のために時間をかける。                   |
| A9   | I feel others' emotions.                        | 私は他人の感情を感じることができる。               |
| A10  | I make people feel at ease.                     | 私は苦労なく人々を安心させられる。                 |


## 誠実性（Conscientiousness）
| 変数 | 質問文（英語）                                           | 質問文（日本語）                                     |
| ---- | -------------------------------------------------------- | ---------------------------------------------------- |
| C1   | I am always prepared.                                    | 私はいつも準備をする。                               |
| C2   | I leave my belongings around.                            | 私は身の回りのものはほったらかしにする（逆転）       |
| C3   | I pay attention to details.                              | 私は細部に注意を払う。                               |
| C4   | I make a mess of things.                                 | 私は物事をぐちゃぐちゃにしてしまう（逆転）           |
| C5   | I get chores done right away.                            | 私はすぐに雑用を済ませる。                           |
| C6   | I often forget to put things back in their proper place. | 私は使ったものを元の場所に戻すのをよく忘れる（逆転） |
| C7   | I like order.                                            | 私は秩序を好む。                                     |
| C8   | I shirk my duties.                                       | 私はやるべきことを怠る（逆転）                       |
| C9   | I follow a schedule.                                     | 私は計画通りに物事をこなす。                         |
| C10  | I am exacting in my work.                                | 私は仕事に追われている。                             |


## 開放性（Openness to experience）
| 変数 | 質問文（英語）                                  | 質問文（日本語）                                           |
| ---- | ----------------------------------------------- | ---------------------------------------------------------- |
| O1   | I have a rich vocabulary.                       | 私は豊かな語彙を持つ。                                     |
| O2   | I have difficulty understanding abstract ideas. | 私にとって抽象的なアイディアを理解するのは難しい。（逆転） |
| O3   | I have a vivid imagination.                     | 私は行き来とした想像力を持つ。                             |
| O4   | I am not interested in abstract ideas.          | 私は抽象的なことには興味がない。（逆転）                   |
| O5   | I have excellent ideas.                         | 私には素晴らしいアイディアがある。                         |
| O6   | I do not have a good imagination.               | 私には豊かな想像力がない。（逆転）                         |
| O7   | I am quick to understand things.                | 私は物事をすぐに理解できる。                               |
| O8   | I use difficult words.                          | 私は難しい言葉を使う。                                     |
| O9   | I spend time reflecting on things.              | 私は物事をじっくり考える。                                 |
| O10  | I am full of ideas.                             | 私にはたくさんのアイディアがある。                         |


## 人種
| 番号 | 人種                                                     |
| ---- | -------------------------------------------------------- |
| 1    | Mixed Race                                               |
| 2    | Arctic (Siberian, Eskimo)                                |
| 3    | Caucasian (European)                                     |
| 4    | Caucasian (Indian)                                       |
| 5    | Caucasian (Middle East)                                  |
| 6    | Caucasian (North African, Other)                         |
| 7    | Indigenous Australian                                    |
| 8    | Native American                                          |
| 9    | North East Asian (Mongol, Tibetan, Korean Japanese, etc) |
| 10   | Pacific (Polynesian, Micronesian, etc)                   |
| 11   | South East Asian (Chinese, Thai, Malay, Filipino, etc)   |
| 12   | West African, Bushmen, Ethiopian                         |
| 13   | Other                                                    |